server:
  port: ${demo-cart-service.server.port}

eureka:
  client:
    service-url:
      defaultZone: ${demo-service-discovery.server.address}/eureka/
    fetch-registry: true
    register-with-eureka: true

spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/learning
    username: root
    password: root