server:
  port: ${demo-user-service.server.port}

#spring:
#  cloud:
#    loadbalancer:
#      ribbon:
#        enabled: false

eureka:
  client:
    service-url:
      defaultZone: ${demo-service-discovery.server.address}/eureka/
    fetch-registry: true
    register-with-eureka: true