server:
  port: ${demo-user-service.server.port}
  host: ${global.host}

eureka:
  instance:
    instanceId: demo-user-service
  client:
    service-url:
      defaultZone: ${demo-service-discovery.server.address}/eureka/
    fetch-registry: true
    register-with-eureka: true