spring:
  application:
    name: ${demo-service-discovery.application.name}

server:
  port: ${demo-service-discovery.server.port}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
    fetch-registry: false
    register-with-eureka: false