server:
  port: ${demo-service-discovery.server.port}
  host: ${global.host}

eureka:
  client:
    service-url:
      defaultZone: ${demo-service-discovery.server.address}/eureka/
    fetch-registry: false
    register-with-eureka: false