server:
  port: ${demo-api-gateway.server.port}

eureka:
  client:
    service-url:
      defaultZone: ${demo-service-discovery.server.address}/eureka/
    fetch-registry: true
    register-with-eureka: true

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: demo-user-service
          uri: lb://demo-user-service
          predicates:
            - Path=/user/**
        - id: demo-cart-service
          uri: lb://demo-cart-service
          predicates:
            - Path=/cart/**
          filters:
            - name: StripPrefix
              args:
                parts: 1
      enabled: true
      default-filters:
        - AddResponseHeader=X-Response-Default, Default-Response-For-All-Routes