server:
  port: ${demo-api-gateway.server.port}

eureka:
  instance:
    instanceId: demo-api-gateway
  client:
    service-url:
      defaultZone: ${demo-service-discovery.server.address}/eureka/
    fetch-registry: true
    register-with-eureka: true

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: demo-user-service
          uri: lb://demo-user-service
          predicates:
            - Header=App-name, demo-user-service
        - id: demo-user-service
          uri: lb://demo-cart-service
          predicates:
            - Header=App-name, demo-cart-service
      enabled: true
      default-filters:
        - AddResponseHeader=X-Response-Default, Default-Response-For-All-Routes